### PR TITLE
lib/fetch/http.c: send proxy auth on https as connect header.

### PR DESCRIPTION
**Pull request by Gottox**

### CODE REVIEW

**Comment by Gottox** [comment]
@pulux: please check this branch.

**Comment by pulux** [comment]
Fixed this issue.

`http_proxy` must be set, `https_proxy` will be ignored.
```
$ export http_proxy=http://>user>:<pass>@170.aa.bb.cc:8080/
$ /usr/local/bin/xbps-uhelper fetch https://repo.voidlinux.eu/logos/void.svg
looking up 170.aa.bb.cc
connecting to 170.aa.bb.cc:8080
SSL options: 83004bff
Peer verification enabled
Using CA cert path: /usr/lib/ssl/certs
Verify hostname
TLSv1.2 connection established using ECDHE-RSA-AES256-GCM-SHA384
Certificate subject: /CN=repo.voidlinux.eu
Certificate issuer: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
requesting https://repo.voidlinux.eu/logos/void.svg
void.svg: 6998B [avg rate: 145MB/s]
```

ty

**Comment by Gottox** [comment]
@xtraeme do you think that we should honor the https_proxy environment variable?

**Comment by pulux** [comment]
Is it possible to backport this into the actual version, then all repos are on https.

**Pull request merged**
