### PR TITLE
Use getopt_long instead of getopt, for musl.

### PR DESCRIPTION
**Pull request by CMB**

### CODE REVIEW

**Comment by xtraeme** [comment]
Please fix the build issues reported by travis.

**Comment by CMB** [comment]
Juan RP <notifications@github.com> writes:

> Please fix the build issues reported by travis.

Where do I find those?
Sorry for asking and looking a bit silly, but I'm blind, doing all this
github stuff with command-line tools, email, and a text browser.
I tried a build locally and didn't see any compiler warnings etc.

**Comment by Gottox** [comment]
https://travis-ci.org/voidlinux/xbps/builds/67633949

**Comment by chneukirchen** [comment]
Enno Boland <notifications@github.com> writes:

> https://travis-ci.org/voidlinux/xbps/builds/67633949

Travis is terrible for blind people.  And people which cannot read
ANSI escape sequences.

https://s3.amazonaws.com/archive.travis-ci.org/jobs/67633950/log.txt

main.c: In function â€˜mainâ€™:
main.c:110:9: error: missing initializer [-Werror=missing-field-initializers]
main.c:110:9: error: (near initialization for â€˜longopts[0].has_argâ€™) [-Werror=missing-field-initializers]
cc1: all warnings being treated as errors

https://s3.amazonaws.com/archive.travis-ci.org/jobs/67633951/log.txt

 [CC]		main.o
main.c:110:32: error: missing field 'has_arg' initializer
      [-Werror,-Wmissing-field-initializers]
        struct option longopts[] = {{0}};

Hope this helps,
-- 
Christian Neukirchen  <chneukirchen@gmail.com>  http://chneukirchen.org

**Comment by CMB** [comment]
> Travis is terrible for blind people. And people which cannot read
> ANSI escape sequences.
*SNIP*
> Hope this helps,

Thank you!  All fixed now.  I also figured out how to interact with travis
from my terminal.  Basically gem install travis, and then travis show to
see info about a build and travis logs to see the logs.

**Pull request merged**
