### PR TITLE
Added xbps-search to search packages from repository in cmd

### PR DESCRIPTION
**Pull request by themester**
(https://voidlinux.eu/packages)

### CODE REVIEW

**Comment by Gottox** [comment]
We won't introduce a pyhon dependency for the package manager. Also voidlinux.eu/packages is considered a hack.

**Comment by ebfe** [comment]
xbps-query can already do that with "-R".

**Comment by themester** [comment]
@Gottox This is not a python dependency. It's Golang, not python.
https://benchmarksgame.alioth.debian.org/u64q/compare.php?lang=go&lang2=python3

**Comment by themester** [comment]
@ebfe This program check the package in the official repository. I invite you to clone it and test it  :)

**Comment by Gottox** [comment]
Oh, sorry right. But it's still redundant as @ebfe stated. No chance to merge.

**Comment by themester** [comment]
Is not the same. I list all disponible repositories from webpage. The program only list my current repository. And I list all package that contains the key phrase, not only one package. I insist that you should test it.

**Comment by ebfe** [comment]
> Is not the same. I list all disponible repositories from webpage. The program only list my current repository.

Which is a sane default. If you want to query other repositories you can do so with --repository=...

> And I list all package that contains the key phrase, not only one package. 

So does xbps-query -s.

> I insist that you should test it.

Did you ever try `xbps-query -Rs vim`?

It's not that this util isn't useful to some extend, in fact i have a similar one (though it uses the repo indexes as data source and also matches properties), but that doesn't mean it has to live in the xbps repo. In particular if it introduces an dependency on another language and doesn't do much more than xbps-query already does.

**Pull request closed without merging**
