### PR TITLE
lib: fix xbps_dbg_printf arguments

### PR DESCRIPTION
**Pull request by ebfe**

### CODE REVIEW

**Comment by chneukirchen** [comment]
It may be a good idea to figure out the __attribute__ to make gcc find these things itself in the future.

**Comment by ebfe** [comment]
```diff
diff --git a/include/xbps.h.in b/include/xbps.h.in
index 13923eb..fb5f077 100644
--- a/include/xbps.h.in
+++ b/include/xbps.h.in
@@ -634,10 +634,10 @@ struct xbps_handle {
 	int flags;
 };
 
-void xbps_dbg_printf(struct xbps_handle *, const char *, ...);
-void xbps_dbg_printf_append(struct xbps_handle *, const char *, ...);
-void xbps_error_printf(const char *, ...);
-void xbps_warn_printf(const char *, ...);
+void xbps_dbg_printf(struct xbps_handle *, const char *, ...) __attribute__ ((format (printf, 2, 3)));
+void xbps_dbg_printf_append(struct xbps_handle *, const char *, ...)__attribute__ ((format (printf, 2, 3)));
+void xbps_error_printf(const char *, ...)__attribute__ ((format (printf, 1, 2)));
+void xbps_warn_printf(const char *, ...)__attribute__ ((format (printf, 1, 2)));
 
 /**
  * Initialize the XBPS library with the following steps:
```

**Comment by xtraeme** [comment]
And what's the reason for this change, can you please explain?

**Comment by chneukirchen** [comment]
gcc will now warn you when you forget a printf argument. :) (try it!)

**Comment by ebfe** [comment]
I experienced segfaults when running xbps with debug output enabled, this PR fixes them. The diff above is the patch I used to track down the faulty printfs. The diff is not included in the PR since it triggers errors in more (harmless) cases. For more information on the format attribute see https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes

**Pull request closed without merging**
